### ISSUE TITLE
《TLS协议分析 与 现代加密通信协议设计》发现一处笔误

### ISSUE THREAD

**Issue by BoringApp** [byronhe/byronhe.github.io#1]
文中：“ECDHE_RSA 密钥交换算法的 SignatureAlgorithm 是 rsa 。 **ECDHE_RSA** 密钥交换算法的 SignatureAlgorithm 是 ecdsa。”
这里是不是出现了笔误？我理解的想表达的意思是：”ECDHE_RSA 密钥交换算法的 SignatureAlgorithm 是 rsa 。 **ECDHE_ECDSA** 密钥交换算法的 SignatureAlgorithm 是 ecdsa。“

**Comment by byronhe** [comment]
你说得对，是个笔误，已经改正，多谢指出。
